debug: true

logger:
  level: 1

server:
  host: 0.0.0.0
  port: 9000
  verbose: true

database:
  host: localhost
  port: 3306
  name: horde
  user: root
  password: liuyanggg.123

redis:
  host: localhost
  port: 6379
  password:

session:
  ttl: 3600